### PR TITLE
docs(swagger): fix Swagger annotations to match actual API contracts

### LINKED ISSUE #88: [Docs] Swagger annotations don't match actual Spring request/response contracts
# [Docs] Swagger annotations don't match actual Spring request/response contracts

## 📋 Problem
Swagger/OpenAPI annotations across several controllers are either **incorrect or missing**, causing the generated API docs to diverge from what Spring actually sends and receives.

---

### 🚨 HIGH — Wrong field names in examples
**`ProjectController`** (`POST /api/v1/projects`)
* **Request:** Example uses `title` and `summary` — actual `CreateProjectCommand` has `projectName`, no `summary` field.
* **Response:** Example uses `title` and `status` — actual `CreateProjectCommandResult` has `projectName`, no `status` field.

### ⚠️ MEDIUM — Missing `@Operation` / `@Parameter`

**`SearchController`** (`GET /api/v1/search/projects`)
* No `@Operation` annotation at all.
* Query params `q`, `status`, `tags`, `page`, `size` have no `@Parameter` docs.
* Jakarta validation constraints (`@NotBlank`, `@Size`) are present but won't appear in Swagger UI without explicit annotations.

**`AdminController`** (`GET /api/v1/admin/users`)
* `@Operation` exists but `page`, `size`, `role`, `isActive`, `search` params are undocumented.

**`UserController`** (`DELETE /api/v1/users/me`)
* `reason` query parameter has no `@Parameter` annotation.

---

## ✨ Expected Behavior
Swagger UI should accurately reflect the fields, types, and constraints that the API actually accepts and returns.

---

## ✅ Scope & Tasks
- [ ] Fix field name mismatches in `ProjectController` examples.
- [ ] Add `@Operation` + `@Parameter` to `SearchController`.
- [ ] Add `@Parameter` to undocumented query params in `AdminController`.
- [ ] Add `@Parameter` to `reason` in `UserController.deactivateAccount`.
- [ ] Verify `FileController` upload response example matches actual handler output.

## Note                                                                  
                                                                           
  Only a subset of controllers were reviewed. A full audit of all          
  controllers                                               
  is needed before closing this issue — other endpoints may have similar   
  mismatches.                                                              
   
  Controllers to audit:                                                    
  - [ ] `ProjectController`                                 
  - [ ] `AuthController`                                                   
  - [ ] `UserController`
  - [ ] `SearchController`                                                 
  - [ ] `AdminController`                                   
  - [ ] `FileController`
  - [ ] `HealthController`
  - [ ] `ElasticsearchAdminController`  
---
**Related to:** #12 (Complete Project Management Commands and Queries)

### PR DESCRIPTION
**Pull request by Deniz1923**
## Summary
  - Fixed field name mismatches in ProjectController request/response examples (`title`→`projectName`, removed
  non-existent `summary`/`status` fields)
  - Added `@Operation`, `@Parameter`, and `@ApiResponse` to all 3 SearchController endpoints (previously completely
  undocumented)
  - Added `@Parameter` annotations to ~20 undocumented path/query params across AdminController's 35+ endpoints
  - Added full documentation to AuthController's `refreshToken` endpoint and `@Parameter` to `verify-email` token param
  - Added `@Parameter` to UserController (`userId`, `reason`) and FileController (`path`)
  - Added `@Tag`, `@Operation`, `@SecurityRequirement`, and `@ApiResponse` to all 3 ElasticsearchAdminController
  endpoints (previously completely undocumented)
  - Added `@ApiResponse` with example to HealthController
  
  Closes #88 

  ## Test plan
  - [ ] Run the application and verify Swagger UI at `/swagger-ui.html` renders correctly
  - [ ] Confirm ProjectController create endpoint shows `projectName` (not `title`) in examples
  - [ ] Confirm SearchController endpoints now appear with full parameter docs
  - [ ] Confirm AdminController query/path params are visible in Swagger UI
  - [ ] Confirm ElasticsearchAdminController endpoints appear under "Elasticsearch Admin" tag
  - [ ] Verify `./gradlew compileJava` passes (verified locally)

### CODE REVIEW

**Comment by Deniz1923** [comment]
@uncorrupt0 review

File: src/main/java/com/iyte_yazilim/proje_pazari/presentation/controllers/ProjectController.java [hunk 1]
```diff
@@ -40,14 +45,70 @@ public class ProjectController extends BaseController {
...
+                                                    """
+            {
+                "projectName": "AI Chatbot Project",
+                "description": "Building an AI-powered chatbot for customer support using modern NLP techniques.",
+                "maxTeamSize": 5,
+                "requiredSkills": ["Python", "NLP", "Machine Learning", "FastAPI"],
+                "category": "Artificial Intelligence",
+                "deadline": "2025-06-15T23:59:59"
+            }
+            """)))
```
Comment (uncorrupt0) [inline src/main/java/com/iyte_yazilim/proje_pazari/presentation/controllers/ProjectController.java:116]:
```java
// The example JSON is missing `ownerId`:
{
    "projectName": "AI Chatbot Project",
    "description": "...",
    // ownerId is @NotBlank in CreateProjectCommand — add it here
    // or document in @Operation that ownerId is resolved from the bearer token
}
```

**Suggestion:**
- If `ownerId` is sent by the client: add `"ownerId": "01HQXV5KXBW9FYMN8CJZSP2R4G"` to the example.
- If `ownerId` is resolved server-side from JWT: remove the `@NotBlank` constraint (or set via handler before validation), and add a note to the `@Operation` description: "The `ownerId` is resolved from the authenticated user's token — do not include in the request body."

File: src/main/java/com/iyte_yazilim/proje_pazari/presentation/controllers/AdminController.java [hunk 2]
```diff
@@ -231,7 +292,8 @@ public ResponseEntity<ApiResponse<PagedResponse<ApplicationAdminDTO>>> listAppli
             description = "Admin review of any application (approve/reject)")
     @Audited(action = "ADMIN_REVIEW_APPLICATION", entityType = "APPLICATION")
     public ResponseEntity<ApiResponse<Void>> reviewApplication(
-            @PathVariable String applicationId,
+            @Parameter(description = "Application ID", required = true) @PathVariable
```
Comment (uncorrupt0) [inline src/main/java/com/iyte_yazilim/proje_pazari/presentation/controllers/AdminController.java]: Missing `example`. Suggestion:
```java
@Parameter(description = "Application ID", required = true, example = "01HQXV5KXBW9FYMN8CJZSP2R5A")
    @PathVariable String applicationId,
```

File: src/main/java/com/iyte_yazilim/proje_pazari/presentation/controllers/AdminController.java [hunk 3]
```diff
@@ -493,7 +584,10 @@ public ResponseEntity<ApiResponse<List<ActiveSessionDTO>>> getActiveSessions() {
             summary = "Invalidate user sessions",
             description = "Revoke all sessions for a specific user")
     @Audited(action = "INVALIDATE_USER_SESSIONS", entityType = "SESSION")
-    public ResponseEntity<ApiResponse<Void>> invalidateUserSessions(@PathVariable String userId) {
+    public ResponseEntity<ApiResponse<Void>> invalidateUserSessions(
+            @Parameter(description = "User ID whose sessions to invalidate", required = true)
+                    @PathVariable
+                    String userId) {
```
Comment (uncorrupt0) [inline src/main/java/com/iyte_yazilim/proje_pazari/presentation/controllers/AdminController.java]: Missing `example`. Suggest:
```java
@Parameter(description = "User ID whose sessions to invalidate", required = true,
           example = "01HQXV5KXBW9FYMN8CJZSP2R4G")
    @PathVariable String userId) {
```

File: src/main/java/com/iyte_yazilim/proje_pazari/presentation/controllers/HealthController.java [hunk 4]
```diff
@@ -19,6 +22,27 @@ public class HealthController {
...
+                                @Content(
+                                        mediaType = "application/json",
+                                        examples =
+                                                @ExampleObject(
+                                                        name = "Healthy",
+                                                        value =
+                                                                """
+                    {
+                        "status": "UP",
+                        "timestamp": "2025-03-25T12:00:00",
```
Comment (uncorrupt0) [inline src/main/java/com/iyte_yazilim/proje_pazari/presentation/controllers/HealthController.java]: Suggest changing to a clearly illustrative future/neutral date, e.g. `"2026-01-01T12:00:00"`, or annotate the example name as `"Example Response (timestamp is dynamic)"`.

**Review by uncorrupt0 — CHANGES_REQUESTED** [review]
# Code Review — PR #89: `fix/swagger-annotations-audit`

**Issue:** #88 — Swagger annotations don't match actual Spring request/response contracts
**Branch:** `fix/swagger-annotations-audit` → `dev`
**Reviewer:** Code review pass (2026-03-25)

---

## CI Status

| Check | Result |
|---|---|
| Code Quality & Formatting | ✅ SUCCESS |
| Validate Pull Request | ✅ SUCCESS |
| Build & Test | ✅ SUCCESS |

All CI checks pass.

---

## Issue Acceptance Criteria

| Criterion | Status |
|---|---|
| Fix field name mismatches in `ProjectController` examples (`title`→`projectName`, remove `summary`/`status`) | ✅ Done |
| Add `@Operation` + `@Parameter` to `SearchController` | ✅ Done |
| Add `@Parameter` to undocumented query params in `AdminController` | ✅ Done |
| Add `@Parameter` to `reason` in `UserController.deactivateAccount` | ✅ Done |
| Verify `FileController` upload response example matches actual handler | ✅ Audited (`@Parameter` added to download path) |
| Full audit of all 8 listed controllers | ✅ All covered |

**Beyond scope (positive):**
- `ElasticsearchAdminController` — fully documented (`@Tag`, `@Operation`, `@SecurityRequirement`, `@ApiResponses`) when issue only listed it for audit
- `AuthController.refreshToken` — added complete `@Operation`/`@ApiResponses` when endpoint had zero documentation

---

## Findings

### 🔴 High — Request body example missing required `ownerId` field

**File:** `ProjectController.java` — `POST /api/v1/projects` `@RequestBody` example

The `CreateProjectCommand` record has:
```java
@NotBlank(message = "Owner ID is required")
String ownerId,
```

But the new request body example omits `ownerId`:
```json
{
    "projectName": "AI Chatbot Project",
    "description": "...",
    "maxTeamSize": 5,
    "requiredSkills": ["Python", ...],
    "category": "Artificial Intelligence",
    "deadline": "2025-06-15T23:59:59"
}
```

Any developer clicking **"Try it out"** in Swagger UI with this example will get a `400 BAD_REQUEST` validation error. This defeats the purpose of the documentation fix.

**Fix:** Add `ownerId` to the example, or document it as auth-populated if the handler extracts it from the JWT (in which case, add a note in the `@Operation` description clarifying that `ownerId` is resolved server-side from the bearer token).

---

### 🟡 Medium — Inconsistent `example` values on path variable `@Parameter` annotations in `AdminController`

Most path-variable parameters include a ULID example, but several do not:

| Endpoint | Parameter | Has example? |
|---|---|---|
| `PUT /admin/applications/{applicationId}/review` | `applicationId` | ❌ No |
| `POST /admin/content/review/{flagId}` | `flagId` | ❌ No |
| `DELETE /admin/users/{userId}/sessions` | `userId` | ❌ No |
| `DELETE /admin/scheduled-emails/{id}` | `id` | ❌ No |
| `POST /admin/content/{type}/{id}/flag` | `id` | ❌ No |

Compare with `getUser`, `deleteUser`, `updateUser`, `deleteProject`, `featureProject`, `unbanIp` — all include `example = "01HQXV5KXBW9FYMN8CJZSP2R4G/H"`. The inconsistency makes the documentation feel incomplete for admin-heavy endpoints that are particularly hard to explore manually.

**Fix:** Add a representative ULID example to each missing `@Parameter`.

---

### 🟡 Medium — `HealthController` example timestamp hardcoded to past date

**File:** `HealthController.java:40`

```java
"timestamp": "2025-03-25T12:00:00",
```

Today is 2026-03-25. The example was written with a 2025 timestamp, which already looks stale. The actual handler uses `LocalDateTime.now()` so the response is dynamic, but the Swagger example will forever show a year-old timestamp to anyone reading the docs.

**Fix:** Update to a plausible example date, or note in the `@ExampleObject` name that it is illustrative (e.g., name = `"Example (timestamp is dynamic)"`).

---

### 🟢 Low — `SearchController.searchProjects` `status` param typed as `String` instead of enum

**File:** `SearchController.java` — `GET /api/v1/search/projects`

```java
@Parameter(description = "Filter by project status (e.g. OPEN, DRAFT, IN_PROGRESS)", example = "OPEN")
@RequestParam(required = false) String status,
```

The description manually lists valid values, but Swagger UI will render a free-text input rather than a dropdown. The `AdminController`'s equivalent parameter uses `ProjectStatus` (an enum), which gives automatic dropdown selection.

This may be intentional if the search endpoint accepts a superset of status strings (e.g., Elasticsearch status values differ), but if it mirrors `ProjectStatus`, using the enum type would give better UX.

**Not a blocker** — worth a follow-up issue if the status values are the same enum.

---

## Positive Observations

- **Comprehensive scope:** 8 controllers fully audited, not just the 5 in the original issue task list. The PR title and description accurately reflect this expanded scope.
- **Correct conventional commit:** `feat(docs): ...` is appropriate. Swagger annotation changes are not functional changes, so `feat(docs)` or `docs(swagger)` are both valid.
- **`@SecurityRequirement` on ElasticsearchAdminController:** Added correctly at the class level, consistent with `AdminController` and `UserController` patterns.
- **`AuthController.refreshToken`:** The added `@Operation` description ("Use this when the current access token has expired") is genuinely useful for API consumers who may confuse refresh with re-login flows.
- **AOSP formatting preserved:** `spotlessCheck` passes, so the annotation style is consistent with project conventions.

File: src/main/java/com/iyte_yazilim/proje_pazari/presentation/controllers/ProjectController.java [hunk 5]
```diff
@@ -35,19 +40,80 @@ public class ProjectController extends BaseController {
...
                         responseCode = "401",
                         description = "Unauthorized")
             })
+    @io.swagger.v3.oas.annotations.parameters.RequestBody(
+            description = "Project creation details",
+            required = true,
+            content =
+                    @Content(
+                            mediaType = MediaType.APPLICATION_JSON_VALUE,
+                            schema = @Schema(implementation = CreateProjectCommand.class),
```
Comment (uncorrupt0) [inline src/main/java/com/iyte_yazilim/proje_pazari/presentation/controllers/ProjectController.java:102]: Heads-up: SpringDoc will render `ownerId` as required in the schema model tab because of `@NotBlank`. The `@Operation` description correctly explains the server-side resolution, but the schema and example still conflict visually. Consider opening a follow-up issue to add `@Schema(accessMode = Schema.AccessMode.READ_ONLY)` on `ownerId` in `CreateProjectCommand` to hide it from the generated request schema.

File: src/main/java/com/iyte_yazilim/proje_pazari/presentation/controllers/AuthController.java [hunk 6]
```diff
@@ -291,8 +295,24 @@ public ResponseEntity<ApiResponse<Void>> resendVerification(
...
+                @io.swagger.v3.oas.annotations.responses.ApiResponse(
+                        responseCode = "200",
+                        description = "Token refreshed successfully"),
+                @io.swagger.v3.oas.annotations.responses.ApiResponse(
+                        responseCode = "400",
+                        description = "Invalid or expired refresh token")
+            })
     public ResponseEntity<ApiResponse<RefreshTokenResult>> refreshToken(
-            @RequestParam String refreshToken) {
+            @Parameter(description = "Refresh token obtained during login", required = true)
```
Comment (uncorrupt0) [inline src/main/java/com/iyte_yazilim/proje_pazari/presentation/controllers/AuthController.java]: Minor: This is the only `required = true` parameter in the file without an example value. Adding a placeholder token string (even a truncated JWT example) would make "Try it out" less friction-heavy for developers testing the endpoint.

**Review by uncorrupt0 — APPROVED** [review]
# Code Review — PR #89: `feat(docs): fix Swagger annotations to match actual API contracts`

**Issue:** #88 — Swagger annotations don't match actual Spring request/response contracts
**Branch:** `fix/swagger-annotations-audit` → `dev`
**Review date:** 2026-03-26

---

## CI Status

| Check | Result |
|---|---|
| Code Quality & Formatting | ✅ SUCCESS |
| Validate Pull Request | ✅ SUCCESS |
| Build & Test | ✅ SUCCESS |

All CI checks pass.

---

## Previous Review Follow-up (CHANGES_REQUESTED by @uncorrupt0, 2026-03-25)

The latest commit (`6be98fd`) directly addressed every finding from the prior review. Here is the verification:

| Finding | Status |
|---|---|
| 🔴 High: `ownerId` missing from request example — developers using "Try it out" would receive 400 | ✅ Fixed: `@Operation` description now explicitly states "The ownerId is resolved server-side from the authenticated user's bearer token — do not include it in the request body." |
| 🟡 Medium: Inconsistent ULID examples on `AdminController` path variables (`applicationId`, `flagId`, `userId` for sessions, scheduled email `id`, content `id`) | ✅ Fixed: All five parameters now have ULID examples. |
| 🟡 Medium: `HealthController` example timestamp hardcoded to past date (`2025-03-25`) | ✅ Fixed: Updated to `2026-01-01T12:00:00` and `@ExampleObject` name clarified to `"Healthy (timestamp is dynamic)"`. |
| 🟢 Low: `SearchController.searchProjects` `status` typed as `String` rather than `ProjectStatus` enum | Not addressed — accepted as known limitation, no dropdown in Swagger UI. Not a blocker. |

---

## Issue #88 Acceptance Criteria

| Criterion | Status |
|---|---|
| Fix field name mismatches in `ProjectController` examples (`title`→`projectName`, remove `summary`/`status`) | ✅ Done |
| Add `@Operation` + `@Parameter` to `SearchController` | ✅ Done |
| Add `@Parameter` to undocumented query params in `AdminController` | ✅ Done |
| Add `@Parameter` to `reason` in `UserController.deactivateAccount` | ✅ Done |
| Verify `FileController` upload response example matches actual handler | ✅ Audited — `@Parameter` added to `downloadFile` path variable |
| Full audit of all 8 listed controllers | ✅ All covered |

**Beyond scope (positive additions):**
- `ElasticsearchAdminController` — fully annotated with `@Tag`, `@Operation`, `@SecurityRequirement`, and `@ApiResponses` (three endpoints that had zero documentation)
- `AuthController.refreshToken` — complete `@Operation` and `@ApiResponses` added to a previously undocumented endpoint
- `ProjectController.createProject` — full request/response `@ExampleObject` with correct field names, and a 400 validation error example

---

## New Findings

### 🟢 Low — `ownerId` schema conflicts with example in `ProjectController`

**File:** `ProjectController.java:111–131` / `CreateProjectCommand.java:65–67`

The `@io.swagger.v3.oas.annotations.parameters.RequestBody` uses `@Schema(implementation = CreateProjectCommand.class)`. SpringDoc reads `@NotBlank` on `ownerId` and marks it as **required** in the generated JSON Schema (the "Model" tab in Swagger UI). Meanwhile, the request example omits `ownerId` and the `@Operation` description says not to include it.

A developer using Swagger UI will see a contradiction:
- Schema (required): `ownerId: string` ← from `@NotBlank`
- Example: no `ownerId` field
- Description: "do not include it in the request body"

The underlying security is sound — `AutoRequestMapper.injectAuthFields()` (`AutoRequestMapper.java:168–172`) always overwrites `ownerId` from the authenticated `UserPrincipal`, so a client sending `{"ownerId": "other_user_id", ...}` cannot impersonate another user.

The documentation inconsistency can be resolved in a follow-up issue by adding `@Schema(hidden = true)` or `@Schema(accessMode = Schema.AccessMode.READ_ONLY)` to the `ownerId` field in `CreateProjectCommand`. This PR's chosen approach (prose in `@Operation` description) is an acceptable short-term fix.

**Recommendation:** Open a follow-up issue. Not a blocker for this PR.

---

### 🔵 Informational — `AuthController` logout endpoint appears in diff

The `POST /auth/logout` endpoint appears in `gh pr diff 89` for `AuthController.java`. This code originates from PR #85 (feature/logout) and entered this branch via the `origin/dev` merge at commit `aadb1e3`. It is not part of the Swagger annotation work.

The logout endpoint's annotations are well-structured (`@Operation`, `@ApiResponses`, `@SecurityRequirement`, `@PreAuthorize`). No issues there. This is a GitHub diff artefact from the merge-base calculation and does not require any action.

---

### ✏️ Nit — `refreshToken` `@Parameter` has no example value

**File:** `AuthController.java:379`

```java
@Parameter(description = "Refresh token obtained during login", required = true)
```

Other token/id parameters across the PR include example values. This parameter does not. The difference is minor but adds friction in Swagger UI's "Try it out" mode.

**Suggestion:** Add `example = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."` or any representative placeholder. Non-blocking.

---

### ✏️ Nit — Commit type without scope

The PR title uses `feat(docs):` (which implies a new documentation *feature*) while most of the changes are corrections to wrong or absent annotations. The latest commit `6be98fd` uses `fix:` without a scope. Project conventions per CLAUDE.md specify `<type>(<scope>):` format.

`docs(swagger):` or `fix(swagger):` would be more precise. Non-blocking.

---

## Positive Observations

- **Security verified:** `AutoRequestMapper.java:21–22` defines `AUTH_USER_FIELDS = Set.of("userId", "ownerId", ...)`. The `injectAuthFields` call at line 74 runs *after* body data is loaded and always overwrites these fields from the authenticated principal. The `ownerId` documentation change is accurate.
- **Coverage:** 8 controllers, 35+ endpoints audited. Annotations are consistent in style (`required = true` on path vars, descriptions are imperative, ULID examples use the same format throughout).
- **`ElasticsearchAdminController`:** The `"Use with caution"` warning in the `deleteAllIndexes` description is a good developer safety hint for a destructive endpoint.
- **`AuthController.refreshToken` description:** "Use this when the current access token has expired" clarifies the intent in a way that distinguishes it from re-login, which is genuinely useful for API consumers.
- **AOSP formatting preserved:** `spotlessCheck` passes cleanly.
- **`ProjectController` deadline example:** Corrected from `2025-06-15T23:59:59` to `2026-06-15T23:59:59` — details like this matter for documentation quality.

---

## Summary

All blocking findings from the previous `CHANGES_REQUESTED` review are resolved. The remaining items are Low/informational and suitable for follow-up issues rather than blocking this PR.

**Comment by Deniz1923** [comment]
Done @uncorrupt0
